<!-- General JS Scripts -->
<script src="<?php echo base_url('modules/jquery.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/popper.js'); ?>"></script>
<script src="<?php echo base_url('modules/tooltip.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap/js/bootstrap.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/moment.min.js'); ?>"></script>
<script src="<?php echo base_url('js/stisla.js'); ?>"></script>
  
<!-- JS Libraies -->
<script src="<?php echo base_url('modules/jquery.sparkline.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/chart.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/owlcarousel2/dist/owl.carousel.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/chocolat/dist/js/jquery.chocolat.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/simple-weather/jquery.simpleWeather.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/chart.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/jquery.vmap.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/maps/jquery.vmap.world.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/chocolat/dist/js/jquery.chocolat.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/chocolat/dist/js/jquery.chocolat.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-ui/jquery-ui.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/prism/prism.js'); ?>"></script>
<script src="<?php echo base_url('modules/sticky-kit.js'); ?>"></script>
<script src="<?php echo base_url('modules/chocolat/dist/js/jquery.chocolat.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/dropzonejs/min/dropzone.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery.sparkline.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/chart.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/jquery.vmap.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/maps/jquery.vmap.world.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/maps/jquery.vmap.indonesia.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-ui/jquery-ui.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/owlcarousel2/dist/owl.carousel.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/cleave-js/dist/cleave.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/cleave-js/dist/addons/cleave-phone.us.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-pwstrength/jquery.pwstrength.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap-daterangepicker/daterangepicker.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap-timepicker/js/bootstrap-timepicker.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/select2/dist/js/select2.full.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-selectric/jquery.selectric.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/codemirror/lib/codemirror.js'); ?>"></script>
<script src="<?php echo base_url('modules/codemirror/mode/javascript/javascript.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-selectric/jquery.selectric.min.js'); ?>"></script>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyB55Np3_WsZwUQ9NS7DP-HnneleZLYZDNw&amp;sensor=true"></script>
<script src="<?php echo base_url('modules/gmaps.js'); ?>"></script>
<script src="<?php echo base_url('modules/fullcalendar/fullcalendar.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/chart.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/datatables/datatables.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/datatables/Select-1.2.4/js/dataTables.select.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-ui/jquery-ui.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/owlcarousel2/dist/owl.carousel.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery.sparkline.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/sweetalert/sweetalert.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/izitoast/js/iziToast.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/izitoast/js/iziToast.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/jquery.vmap.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/maps/jquery.vmap.world.js'); ?>"></script>
<script src="<?php echo base_url('modules/jqvmap/dist/maps/jquery.vmap.indonesia.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-pwstrength/jquery.pwstrength.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-selectric/jquery.selectric.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-selectric/jquery.selectric.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/upload-preview/assets/js/jquery.uploadPreview.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/jquery-selectric/jquery.selectric.min.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/codemirror/lib/codemirror.js'); ?>"></script>
<script src="<?php echo base_url('modules/codemirror/mode/javascript/javascript.js'); ?>"></script>
<script src="<?php echo base_url('modules/summernote/summernote-bs4.js'); ?>"></script>
<script src="<?php echo base_url('modules/chocolat/dist/js/jquery.chocolat.min.js'); ?>"></script>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyB55Np3_WsZwUQ9NS7DP-HnneleZLYZDNw&amp;sensor=true"></script>
<script src="<?php echo base_url('modules/gmaps.js'); ?>"></script>


<!-- Page Specific JS File -->
<script src="<?php echo base_url('js/page/index.js'); ?>"></script>
<script src="<?php echo base_url('js/page/index-0.js'); ?>"></script>
<script src="<?php echo base_url('js/page/bootstrap-modal.js'); ?>"></script>
<script src="<?php echo base_url('js/page/components-chat-box.js'); ?>"></script>
<script src="<?php echo base_url('js/page/components-multiple-upload.js'); ?>"></script>
<script src="<?php echo base_url('js/page/components-statistic.js'); ?>"></script>
<script src="<?php echo base_url('js/page/components-table.js'); ?>"></script>
<script src="<?php echo base_url('js/page/components-user.js'); ?>"></script>
<script src="<?php echo base_url('js/page/forms-advanced-forms.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-advanced-route.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-draggable-marker.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-geocoding.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-geolocation.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-marker.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-multiple-marker.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-route.js'); ?>"></script>
<script src="<?php echo base_url('js/page/gmaps-simple.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-calendar.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-chartjs.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-datatables.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-ion-icons.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-slider.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-sparkline.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-sweetalert.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-toastr.js'); ?>"></script>
<script src="<?php echo base_url('js/page/modules-vector-map.js'); ?>"></script>
<script src="<?php echo base_url('js/page/auth-register.js'); ?>"></script>
<script src="<?php echo base_url('js/page/features-post-create.js'); ?>"></script>
<script src="<?php echo base_url('js/page/features-posts.js'); ?>"></script>
<script src="<?php echo base_url('js/page/features-setting-detail.js'); ?>"></script>
<script src="<?php echo base_url('js/page/utilities-contact.js'); ?>"></script>

<script type="text/javascript" src="<?php echo base_url('js/scripts.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('js/custom.js'); ?>"></script>